### ISSUE TITLE
Flushdb and flashall crash the server.

### ISSUE THREAD

**Issue by shkediy** [RedisLabsModules/redis-graph#10]
This is the server console output:

=== REDIS BUG REPORT START: Cut & paste starting from here ===
9033:M 21 Jun 20:36:53.422 # Redis 3.9.103 crashed by signal: 11
9033:M 21 Jun 20:36:53.422 # Crashed running the instuction at: 0x7fc5331e9b98
9033:M 21 Jun 20:36:53.422 # Accessing address: 0x3bf30d0
9033:M 21 Jun 20:36:53.422 # Failed assertion: <no assertion failed> (<no file>:0)

------ STACK TRACE ------
EIP:
/home/ubuntu/redis-4.0-rc3/src/modules/redis-graph/src/redisgraph.so(raxRecursiveFree+0x48)[0x7fc5331e9b98]

Backtrace:
./redis-server 127.0.0.1:6379(logStackTrace+0x45)[0x46a025]
./redis-server 127.0.0.1:6379(sigsegvHandler+0xb9)[0x46a7e9]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x11390)[0x7fc5354df390]
/home/ubuntu/redis-4.0-rc3/src/modules/redis-graph/src/redisgraph.so(raxRecursiveFree+0x48)[0x7fc5331e9b98]

------ INFO OUTPUT ------
# Server
redis_version:3.9.103
redis_git_sha1:00000000
redis_git_dirty:0
redis_build_id:d7d4ab0dbbc9a1c4
redis_mode:standalone
os:Linux 4.4.0-1061-aws x86_64
arch_bits:64
multiplexing_api:epoll
gcc_version:5.4.0
process_id:9033
run_id:95b373a16ffc5badce6a1c708955ec966494208e
tcp_port:6379
uptime_in_seconds:9
uptime_in_days:0
hz:10
lru_clock:2886757
executable:/home/ubuntu/redis-4.0-rc3/src/./redis-server
config_file:/home/ubuntu/redis-4.0-rc3/redis.conf

# Clients
connected_clients:1
client_longest_output_list:0
client_biggest_input_buf:0
blocked_clients:0

# Memory
used_memory:829056
used_memory_human:809.62K
used_memory_rss:18006016
used_memory_rss_human:17.17M
used_memory_peak:951984
used_memory_peak_human:929.67K
used_memory_peak_perc:87.09%
used_memory_overhead:815758
used_memory_startup:765824
used_memory_dataset:13298
used_memory_dataset_perc:21.03%
total_system_memory:15768764416
total_system_memory_human:14.69G
used_memory_lua:37888
used_memory_lua_human:37.00K
maxmemory:0
maxmemory_human:0B
maxmemory_policy:noeviction
mem_fragmentation_ratio:21.72
mem_allocator:jemalloc-4.0.3
active_defrag_running:0
lazyfree_pending_objects:0

# Persistence
loading:0
rdb_changes_since_last_save:0
rdb_bgsave_in_progress:0
rdb_last_save_time:1529613404
rdb_last_bgsave_status:ok
rdb_last_bgsave_time_sec:-1
rdb_current_bgsave_time_sec:-1
rdb_last_cow_size:0
aof_enabled:0
aof_rewrite_in_progress:0
aof_rewrite_scheduled:0
aof_last_rewrite_time_sec:-1
aof_current_rewrite_time_sec:-1
aof_last_bgrewrite_status:ok
aof_last_write_status:ok
aof_last_cow_size:0

# Stats
total_connections_received:2
total_commands_processed:22
instantaneous_ops_per_sec:0
total_net_input_bytes:157808
total_net_output_bytes:5384
instantaneous_input_kbps:0.00
instantaneous_output_kbps:0.00
rejected_connections:0
sync_full:0
sync_partial_ok:0
sync_partial_err:0
expired_keys:0
evicted_keys:0
keyspace_hits:0
keyspace_misses:0
pubsub_channels:0
pubsub_patterns:0
latest_fork_usec:0
migrate_cached_sockets:0
slave_expires_tracked_keys:0
active_defrag_hits:0
active_defrag_misses:0
active_defrag_key_hits:0
active_defrag_key_misses:0

# Replication
role:master
connected_slaves:0
master_replid:a184f08bc53233337269b8ef4dce60abb7fdb2d4
master_replid2:0000000000000000000000000000000000000000
master_repl_offset:0
second_repl_offset:-1
repl_backlog_active:0
repl_backlog_size:1048576
repl_backlog_first_byte_offset:0
repl_backlog_histlen:0

# CPU
used_cpu_sys:0.01
used_cpu_user:0.09
used_cpu_sys_children:0.00
used_cpu_user_children:0.00

# Commandstats
cmdstat_exists:calls=1,usec=1,usec_per_call=1.00

# Cluster
cluster_enabled:0

# Keyspace
db0:keys=6,expires=0,avg_ttl=0

------ CLIENT LIST OUTPUT ------
id=3 addr=127.0.0.1:53002 fd=7 name= age=0 idle=0 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=32768 obl=0 oll=0 omem=0 events=r cmd=flushall

------ CURRENT CLIENT INFO ------
id=3 addr=127.0.0.1:53002 fd=7 name= age=0 idle=0 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=32768 obl=0 oll=0 omem=0 events=r cmd=flushall
argv[0]: 'FLUSHALL'
Segmentation fault (core dumped)

**Comment by swilly22** [comment]
@shkediy you're probably using an old version of the module,
RAX hasn't been introduced just yet to the MATRIX branch.
