### ISSUE TITLE
redis-graph opencypher support and misc questions

### ISSUE THREAD

**Issue by p1nox** [RedisLabsModules/redis-graph#105]
Hi, I just wanted to say that this project is awesome 💯 , after doing some testing I can see how amazingly fast it is ⚡️ 🙌 

I have a couple of questions about redis-graph module:
* Is it tested to work on cluster architecture?
* I know about the clauses supported for opencypher, and I know `SKIP` is not supported yet, only `LIMIT`, but is there way to paginate without using `SKIP`?
* Is it recommended to use [redisgraph-py](https://github.com/RedisLabs/redisgraph-py) package?

Sidenote: I was hesitant to post in [stackoverflow](https://stackoverflow.com/questions/tagged/redisgraph?sort=newest&pageSize=50) because there are only a few questions there, but if there is a better channel to ask these kind of things let me know, sorry for the inconvenient.

**Comment by jeffreylovitz** [comment]
Glad you like the project!

- Support for cluster architectures is on our roadmap, but is not implemented yet.
- You're right that pagination is a bit tricky until we introduce `SKIP` clauses. As a temporary workaround, the easiest solution would be to include a unique identifier as a property in your nodes, then add a matching `WHERE` clause to make paginated queries:
```
CREATE (a:person {name: 'Jim', id: 1})
...
MATCH (a:person) WHERE a.id > 5 RETURN a ORDER BY a.id LIMIT 5
```
Soon we'll introduce logic to make this a bit less roundabout!
- redisgraph-py is our most well-tested client at the moment, though we've recently introduced Java, Ruby, and Go clients as well - https://oss.redislabs.com/redisgraph/#client-libraries
I'd say use whatever is most natural to you and your use case, though! Queries can be passed to `redis-cli` on the command line, or through most Redis clients. The largest benefit the graph clients offer currently is more effectively being able to print and manipulate result sets.
- I'm labeling this thread as `question`, but personally have no issue using GitHub as a forum for discussing the project. Thanks for your interest and your input!

**Comment by swilly22** [comment]
#124 Support for SKIP

**Comment by p1nox** [comment]
Awesome news 🎉 💯
