### ISSUE TITLE
A query with where and not equal (!=), crashes the server

### ISSUE THREAD

**Issue by shkediy** [RedisLabsModules/redis-graph#11]
I modified the first query in the imdb demo to exclude the actor provided as input:
MATCH (n:actor{name:"Nicolas Cage"})-[:act]->(m:movie)<-[:act]-(a:actor)
where n.name != a.name
RETURN a.name, m.title

The server crashed when runnng this query.
Here's the console output:

redis-server: /home/ubuntu/redis-4.0-rc3/src/modules/redis-graph/src/filter_tree/filter_tree.c:300: _applyFilter: Assertion `0' failed.
Aborted (core dumped)

**Comment by swilly22** [comment]
Support for != added to master branch.
