### ISSUE TITLE
unable to load redis-graph module on redis4.0.11 on CentOS 6.8(Final)

### ISSUE THREAD

**Issue by anishGoMMT** [RedisLabsModules/redis-graph#111]
Error:
 Module /opt/redis/redis-graph/src/redisgraph.so failed to load: /opt/redis/redis-graph/src/redisgraph.so: undefined symbol: clock_gettime

Steps performed:
1. Upgrade gcc to gcc4.9.x
2. export LDFLAGS=-lrt
3. make redis-graph
4. make redis4.0.11
5. redis-server --loadmodule /opt/redis/redis-graph/src/redisgraph.so

**Comment by jeffreylovitz** [comment]
Hi @anishGoMMT,

Can you checkout the branch `import-ldflags` and run steps 2, 3, and 5 again?

It makes a slight alteration to the Makefile so that we'll apply the environment variable LDFLAGS.

**Comment by anishGoMMT** [comment]
Worked, Thanks 👍

**Comment by jeffreylovitz** [comment]
Great! We'll merge this (or a similar) fix into the master branch shortly.

We haven't done a lot of testing on CentOS, so please write up any issues you encounter!

**Comment by swilly22** [comment]
Fixed #112
