### ISSUE TITLE
Many connections lead to `malloc_error_break`

### ISSUE THREAD

**Issue by stockholmux** [RedisLabsModules/redis-graph#118]
I'm running three queries for each record in a file:
`MERGE (:Neighbourhood { name:'${record.NEIGHBOURHOOD}'})`
`MERGE (:Pet { kind:'${record.PET_TYPE}', breed: '${record.BREED}', gender:'${record.GENDER}', fixed:'${record.SPAYED_OR_NEUTERED}' })`;
`MATCH (a:Pet), (b:Neighbourhood) WHERE a.kind='${record.PET_TYPE}' AND a.breed='${record.BREED}' AND a.gender='${record.GENDER}' AND a.fixed='${record.SPAYED_OR_NEUTERED}' AND b.name = '${record.NEIGHBOURHOOD}' CREATE (a)-[:resides]->(b)`

Doing testing to see if it would go faster with multiple connection open (x100 connections) I keep running into this error on the Redis Server like:

```
redis-server(94066,0x70000b8c2000) malloc: *** error for object 0x7f92cb014400: pointer being realloc'd was not allocated
*** set a breakpoint in malloc_error_break to debug
```

Running the data set through 6x, I got the same errors except for one time, I got:
```
Function at 0x107e86d90 is replicationFeedMonitors
Function at 0x107f23968 is bit_tohex
Function at 0x107edeec0 is latencyAddSample
Function at 0x107ec5f60 is slowlogPushEntryIfNeeded
Function at 0x107eaef00 is feedAppendOnlyFile
Function at 0x107e86740 is replicationFeedSlaves
Segmentation fault: 11
```

Interestingly, when I added debug logging to my Node process, it slowed down the overall speed and the I was able to ingest more documents. Without logging I got about 1000 records into the data set, with logging I got 3000 into the dataset.

On single connection to Redis, no errors were encountered (105k records).

**Comment by jeffreylovitz** [comment]
Nice catch, @stockholmux! Would you be willing to try checking out the branch `concurrent-keyspace-protection` and running this test again?

A section of code that propagates changes to the Redis keyspace was outside of the region protected by write locks - this branch ought to solve that problem.

**Comment by stockholmux** [comment]
@jeffreylovitz `concurrent-keyspace-protection` Seems to have fixed the problem!

**Comment by jeffreylovitz** [comment]
This fix has been merged into the master branch.
