### ISSUE TITLE
Support paths

### ISSUE THREAD

**Issue by swilly22** [RedisLabsModules/redis-graph#14]
Introduce a path object and implement shortest path.

**Comment by kolpav** [comment]
@swilly22 I see this issue was moved to done is there shortest path implementation somewhere? If not do you plan on adding it in the future? I see you already have BFS so it should be "easy" to add. I would do it myself but this project is bit out of my current capabilities.

**Comment by swilly22** [comment]
Hi @kolpav, @DvirDukhan is currently working on implementing a `Path` object, once we'll have the `Path` data structure I can go ahead and introduce a shortest path algorithm which returns a path object.

**Comment by kolpav** [comment]
@swilly22 Having shortest path algorithm would be awesome. Thanks for quick reply and good luck with implementation. I will be keeping eye on this project 👍
