### ISSUE TITLE
Build fails on OSX

### ISSUE THREAD

**Issue by kdaham** [RedisLabsModules/redis-graph#20]
Tried a build from master branch today on OSX and and got the following.

[  0%] Building C object CMakeFiles/graphblas.dir/Source/GB_AxB_builtin.c.o
In file included from ../redisgraph/deps/GraphBLAS/Source/GB_AxB_builtin.c:19:
../redisgraph/deps/GraphBLAS/Source/GB.h:1527:1: error: thread-local storage is not supported for the current target
_Thread_local extern GB_thread_local_struct GB_thread_local ;
^
1 error generated.

**Comment by swilly22** [comment]
Hi,
I'm also using OSX as my develop machine and experiencing the same issue, for the time being I dynamically linking GraphBLAS.

1. Run `make install` from within the deps/GraphBLAS folder
2. Update src/MAKEFILE to dynamically link GraphBLAS:
redisgraph.so: $(MODULE)
	$(LD) -o $@ $(MODULE) $(SHOBJ_LDFLAGS) -lc -lm -lgraphblas
	Remove GRAPHBLAS from LIBS.

Hopefully we'll be able to statically link on OSX aswell.
