### ISSUE TITLE
Bug that kills redis

### ISSUE THREAD

**Issue by kdaham** [RedisLabsModules/redis-graph#74]
Had a typo in some test-code which crashed redis (rebuild image today just to be sure it wasnt fixed).
As you can see from the queries its just a typo on the node label

127.0.0.1:6379> graph.query graph:test "CREATE(:Test{a:'1',b:'2'})"
1) 1) Labels added: 1
   2) Nodes created: 1
   3) Properties set: 2
   4) "Query internal execution time: 0.120909 milliseconds"
127.0.0.1:6379> graph.query graph:test "MATCH (t:Test) RETURN t"
1) 1) "t.b,t.a"
   2) "2,1"
2) 1) "Query internal execution time: 0.097027 milliseconds"
127.0.0.1:6379> graph.query graph:test "MATCH **(t:Tesr)** RETURN t"
Error: Server closed the connection
(0.69s)
127.0.0.1:6379>

**Comment by jeffreylovitz** [comment]
Can you verify that you're running the code on the head of the master branch? I believe that this bug was fixed in a recent commit:
https://github.com/RedisLabsModules/redis-graph/commit/7f26a5264

It looks like you're running an outdated build, as the result set was recently changed to return rows in array rather than comma-separated format - running your examples, I get:
```
127.0.0.1:6379> graph.query graph:test "CREATE(:Test{a:'1',b:'2'})"
1) (empty list or set)
2) 1) Labels added: 1
   2) Nodes created: 1
   3) Properties set: 2
   4) "Query internal execution time: 0.084504 milliseconds"
127.0.0.1:6379>  graph.query graph:test "MATCH (t:Test) RETURN t"
1) 1) 1) "t.b"
      2) "t.a"
   2) 1) "2"
      2) "1"
2) 1) "Query internal execution time: 0.077561 milliseconds"
127.0.0.1:6379>  graph.query graph:test "MATCH (t:Tesr) RETURN t"
1) 1) 1) "t"
2) 1) "Query internal execution time: 0.044100 milliseconds"
```

**Comment by kdaham** [comment]
You're probably correct, I build against the matrix branch. rebuilding to verify.

**Comment by kdaham** [comment]
Yep it works as expected against current master branch.
