### ISSUE TITLE
Redis Graph - Frequent Crash

### ISSUE THREAD

**Issue by xxGL1TCHxx** [RedisLabsModules/redis-graph#8]
I'm running redis-graph in Docker and am getting frequent crashes.  I have attached the output, so hopefully that helps.  Any idea what's going on here?  I've had this happen about 6 times in the last couple of hours.  In this instance I was just running a create.  Thanks in advance!
[log.txt](https://github.com/RedisLabsModules/redis-graph/files/1985708/log.txt)

**Comment by itamarhaber** [comment]
@xxGL1TCHxx forget it, this is totally reproducible regardless Docker.

```
127.0.0.1:6379> graph.query imdd match(agent)
Error: Server closed the connection
```

**Comment by itamarhaber** [comment]
@swilly22 this happens w/ all 3 commands (QUERY MATCH, not CREATE I guess) when the user supplies a non-existing graph name.

**Comment by swilly22** [comment]
I see, I'll try to get to it ASAP.

**Comment by kdaham** [comment]
Any progress on this case, its somewhat annoying to have redis die when typing a wrong key

**Comment by swilly22** [comment]
@kdaham Can you please elaborate?
Are you issuing a valid query against a none-existing, wrong type key?

**Comment by kdaham** [comment]
Yes for example the above query that you wrote, if I run that against an empty redis it just crashes, and sure the key doesnt exist, but it shouldnt kill redis.

**Comment by swilly22** [comment]
Please retry  against the MATRIX branch, most of the recent development been on that branch,
I should be merging it to master soon.

**Comment by swilly22** [comment]
Merged to master.
