### ISSUE TITLE
Redis crash if graph cant create a sub-key

### ISSUE THREAD

**Issue by kdaham** [RedisLabsModules/redis-graph#87]
Easy way to recreate this is if you already have a sub-key with the same name structure or create a graph and remove the main key and then try and create the graph again.

```
127.0.0.1:6379> graph.query graph "CREATE (c:country)"
1) (empty list or set)
2) 1) Labels added: 1
   2) Nodes created: 1
   3) "Query internal execution time: 0.456493 milliseconds"

127.0.0.1:6379> keys *
1) "redis_graph_store_graph_NODE_country"
2) "graph"
3) "redis_graph_store_graph_NODE_ALL"

127.0.0.1:6379> del graph
(integer) 1

127.0.0.1:6379> graph.query graph "CREATE (c:country)"
Error: Server closed the connection
(0.74s)

127.0.0.1:6379>
```
And as a way of convenience it would be nice to be able to do graph.delete key.

**Comment by swilly22** [comment]
This is a miss-use, users are not expected to run Redis commands along-side RedisGraph,
If you run sudo rm -rf / expect bad things to happen.

**Comment by jeffreylovitz** [comment]
We ought to add a `GRAPH.DELETE` convenience function soon, I'd say.

In the interim, @kdaham, I'd delete a complete graph from the shell with a sequence like:
```
redis-cli DEL [graphname]
redis-cli KEYS "redis_graph_*[graphname]*" | xargs redis-cli DEL
```
This will open a fair few memory leaks, so restart your server!

**Comment by kdaham** [comment]
@jeffreylovitz yeah I do something similar from my junit-tests, where I use more than just redisgraph in the same db, otherwise flushdb is ok.

@swilly22 I would say that its not quite the same kind of misuse to wanting to create something and it crashes because there might be a key there that is in the way, but fine, quick response thats always good.

**Comment by swilly22** [comment]
@kdaham I've added a new GRAPH.DELETE  command:
https://oss.redislabs.com/redisgraph/commands/#graphdelete

Please use that whenever you wish to delete an entire graph, clients update will follow up shortly.
