### ISSUE TITLE
OpenCypher support question

### ISSUE THREAD

**Issue by stanska** [RedisLabsModules/redis-graph#9]
Hello,

congrats on you good work, I think redisgraph has a huge potential!
I want to experiment with redisgraph to find common customer attributes. Let's say we have the following graph schema:
Nodes: Customer, Password, Name
Links: has_name, has_password 
The goal of the task can be to "Count all unique names for customers using given password"
Here is the script to create the graph via redis-cli. Redis version  Redis 4.0.9, redisgraph pulled on 18.5.2018
//nodes
GRAPH.QUERY passmate "CREATE (:Customer{email:'johnson@gmail.com', id:1});"
GRAPH.QUERY passmate "CREATE (:Password{password:'same password'});"
GRAPH.QUERY passmate "CREATE (:Name{first:'George', last:'Johnson'})"
GRAPH.QUERY passmate "CREATE (:Customer{email:'parker@gmail.com', id:2});"
GRAPH.QUERY passmate "CREATE (:Name{first:'Jane', last:'Parker'})"
GRAPH.QUERY passmate "CREATE (:Customer{email:'evens@gmail.com', id:3});"
GRAPH.QUERY passmate "CREATE (:Password{password:'unique password'});"
GRAPH.QUERY passmate "CREATE (:Name{first:'David', last:'Evans'});"
//links
GRAPH.QUERY passmate "MATCH (a:Customer),(b:Password) WHERE a.id = 1 AND b.password = 'same password' CREATE (a)-[r:has_password { timestamp:'11-08-2012' }]->(b);"
GRAPH.QUERY passmate "MATCH (a:Customer),(b:Password) WHERE a.id = 2 AND b.password = 'same password' CREATE (a)-[r:has_password { timestamp:'30-08-2012' }]->(b);"
GRAPH.QUERY passmate "MATCH (a:Customer),(b:Password) WHERE a.id = 3 AND b.password = 'unique password' CREATE (a)-[r:has_password { timestamp:'30-08-2012' }]->(b);"
GRAPH.QUERY passmate "MATCH (a:Customer),(b:Name) WHERE a.id = 1 AND b.first = 'George' AND b.last = 'Johnson' CREATE (a)-[r:has_name { timestamp:'10-08-2012' }]->(b);"
GRAPH.QUERY passmate "MATCH (a:Customer),(b:Name) WHERE a.id = 2 AND b.first = 'Jane' AND b.last = 'Parker' CREATE (a)-[r:has_name { timestamp:'30-08-2012' }]->(b)"
GRAPH.QUERY passmate "MATCH (a:Customer),(b:Name) WHERE a.id = 3 AND b.first = 'David' AND b.last = 'Evans' CREATE (a)-[r:has_name { timestamp:'20-08-2012' }]->(b);"

Now, data structure is: Name<-[has_name]-Customer-[has_password]->Password
We ask for the count of all unique names with "same password" with:

GRAPH.QUERY passmate "MATCH (n:Name)<-[:name]-(c:Customer)-[:has_password]->(p:Password{password:'same password'}) RETURN distinct count(n)"

Result:
127.0.0.1:6379> GRAPH.QUERY passmate "MATCH (n:Name)<-[:has_name]-(c:Customer)-[:has_password]->(p:Password{password:'same password'}) RETURN count(n)"
1) 1) "count(n)\x00"
   2) "3.000000"
   
Here are some more queries and results for more information:
127.0.0.1:6379> GRAPH.QUERY passmate "MATCH (c:Customer)-[:has_password]->(p:Password{password:'same password'}) RETURN p"
1) 1) "p.password\x00"
   2) "same password"
   3) "same password"
2) 1) "Query internal execution time: 0.122000 milliseconds"
127.0.0.1:6379> GRAPH.QUERY passmate "MATCH (n:Name)<-[:has_name]-(c:Customer)-[:has_password]->(p:Password{password:'same password'}) RETURN p"
1) 1) "p.password\x00"
   2) "same password"
   3) "same password"
   4) "same password"
2) 1) "Query internal execution time: 0.113000 milliseconds"
127.0.0.1:6379> GRAPH.QUERY passmate "MATCH (n:Name)<-[:has_name]-(c:Customer)-[:has_password]->(p:Password{password:'same password'}) RETURN count(n)"
1) 1) "count(n)\x00"
   2) "3.000000"
2) 1) "Query internal execution time: 0.172000 milliseconds"
127.0.0.1:6379> GRAPH.QUERY passmate "MATCH (n:Name)<-[:has_name]-(c:Customer)-[:has_password]->(p:Password{password:'any password'}) RETURN count(n)"
1) 1) "count(n)\x00"
   2) "3.000000"
2) 1) "Query internal execution time: 0.170000 milliseconds"
127.0.0.1:6379> GRAPH.QUERY passmate "MATCH (n:Name)<-[:has_name]-(c:Customer)-[:has_password]->(p:Password{password:'any password'}) RETURN p"
1) 1) "p.password\x00"
   2) "any password"
   3) "any password"
   4) "any password"
2) 1) "Query internal execution time: 0.127000 milliseconds"
127.0.0.1:6379> GRAPH.QUERY passmate "MATCH (c:Customer)-[:has_password]->(p:Password{password:'any password'}) RETURN c,p"
1) 1) "c.email,c.id,p.password\x00"
2) 1) "Query internal execution time: 0.134000 milliseconds"
127.0.0.1:6379> GRAPH.QUERY passmate "MATCH (c:Customer)-[:has_password]->(p:Password{password:'same password'}) RETURN c,p"
1) 1) "c.email,c.id,p.password\x00"
   2) "johnson@gmail.com,1.000000,same password"
   3) "parker@gmail.com,2.000000,same password"
2) 1) "Query internal execution time: 0.133000 milliseconds"

But if we make the link in the other direction, from password to customer and name to customer(similar to country visitor example in your docs) i.e : Name-[has_name]->Customer<-[has_password]-Password
//the same nodes
GRAPH.QUERY passmate "CREATE (:Customer{email:'johnson@gmail.com', id:1});"
GRAPH.QUERY passmate "CREATE (:Password{password:'same password'});"
GRAPH.QUERY passmate "CREATE (:Name{first:'George', last:'Johnson'})"
GRAPH.QUERY passmate "CREATE (:Customer{email:'parker@gmail.com', id:2});"
GRAPH.QUERY passmate "CREATE (:Name{first:'Jane', last:'Parker'})"
GRAPH.QUERY passmate "CREATE (:Customer{email:'evens@gmail.com', id:3});"
GRAPH.QUERY passmate "CREATE (:Password{password:'unique password'});"
GRAPH.QUERY passmate "CREATE (:Name{first:'David', last:'Evans'});"
//same links, BUT link other way arround
GRAPH.QUERY passmate "MATCH (a:Customer),(b:Password) WHERE a.id = 1 AND b.password = 'same password' CREATE (b)-[r:has_password { timestamp:'11-08-2012' }]->(a);"
GRAPH.QUERY passmate "MATCH (a:Customer),(b:Password) WHERE a.id = 2 AND b.password = 'same password' CREATE (b)-[r:has_password { timestamp:'30-08-2012' }]->(a);"
GRAPH.QUERY passmate "MATCH (a:Customer),(b:Password) WHERE a.id = 3 AND b.password = 'unique password' CREATE (b)-[r:has_password { timestamp:'30-08-2012' }]->(a);"
GRAPH.QUERY passmate "MATCH (a:Customer),(b:Name) WHERE a.id = 1 AND b.first = 'George' AND b.last = 'Johnson' CREATE (b)-[r:has_name { timestamp:'10-08-2012' }]->(a) ;"
GRAPH.QUERY passmate "MATCH (a:Customer),(b:Name) WHERE a.id = 2 AND b.first = 'Jane' AND b.last = 'Parker' CREATE (b)-[r:has_name { timestamp:'30-08-2012' }]->(a)"
GRAPH.QUERY passmate "MATCH (a:Customer),(b:Name) WHERE a.id = 3 AND b.first = 'David' AND b.last = 'Evans' CREATE (b)-[r:has_name { timestamp:'20-08-2012' }]->(a);"

Again, if we ask for unique names count with "same password"

GRAPH.QUERY passmate "MATCH (n:Name)-[:has_name]->(c:Customer)<-[:has_password]-(p:Password{password:'same password'}) RETURN count(n)"

we got the following result:

127.0.0.1:6379> GRAPH.QUERY passmate "MATCH (n:Name)-[:has_name]->(c:Customer)<-[:has_password]-(p:Password{password:'same password'}) RETURN count(n)"
1) 1) "count(n)\x00"
   2) "1.000000"
   3) "1.000000"
2) 1) "Query internal execution time: 0.166000 milliseconds"
127.0.0.1:6379>
Here are some more queries and results for this particular case:
127.0.0.1:6379> GRAPH.QUERY passmate "MATCH (n:Name)-[:has_name]->(c:Customer)<-[:has_password]-(p:Password{password:'same password'}) RETURN n,p"
1) 1) "n.first,n.last,p.password\x00"
   2) "George,Johnson,same password"
   3) "Jane,Parker,same password"
2) 1) "Query internal execution time: 0.165000 milliseconds"
127.0.0.1:6379> GRAPH.QUERY passmate "MATCH (n:Name)-[:has_name]->(c:Customer)<-[r:has_password]-(p:Password{password:'same password'}) RETURN n,r,p"
1) 1) "n.first,n.last,r.timestamp,p.password\x00"
   2) "George,Johnson,11-08-2012,same password"
   3) "Jane,Parker,30-08-2012,same password"
2) 1) "Query internal execution time: 0.281000 milliseconds"

So in the second link implementation  Name-[has_name]->Customer<-[has_password]-Password, query returns correct result, except for the fact that count should return only one row.
In the first link type, password does not seem to be really linked to Customer.
Questions:
1)Do you think Name<-[has_name]-Customer-[has_password]->Password  should return the same result as  Name-[has_name]->Customer<-[has_password]-Password , with the appropriate query?
2)Can count return always one row (in the first case returns one, but in the second returns 2 with value 1)? Since, if we count 200 nodes, 200 lines will be returned and more data will be returned and used.

Thanks you,
Stanka

**Comment by swilly22** [comment]
Hi @stanska 
You're right with your second link conclusion, unfortunately the current version of RedisGraph doesn't
support patterns in which some node has more then one outgoing edge, such as (DEST1)<-[R1]-(SRC)-[R2]->(DEST2) one of the edges R1 or R2 will be ignored.

This is something which we will defiantly support soon!

With regard to COUNT I suggest for the moment to explicitly specify on which values you which to group,
for example:

`MATCH (n:Name)-[:has_name]->(c:Customer)<-[:has_password]-(p:Password{password:'same password'}) RETURN p.password, count(n.id)`
