### ISSUE TITLE
Extra newline on some error outputs seems to make lettuce wait for more input.

### ISSUE THREAD

**Issue by kdaham** [RedisLabsModules/redis-graph#94]
127.0.0.1:6379> graph.query a "MATCH (c:Country) RETURN c"
(error) key doesn't contains a graph object.
127.0.0.1:6379>

Above works as expected when asking lettuce to parse it as byte[] or List<Object>
But some erroneous commands produces an extra newline which seems(havent debugged it yet) to make lettuce wait for more data, for example this line

127.0.0.1:6379> graph.query a "MATCH (c:Country) RETURN *"
(error) Syntax error at offset 27 near '*'

127.0.0.1:6379>

Will make it seemingly block for more data, I imagine it is supposed to be just one newline like the first example.

A minor detail on the first error-line, it should probably ready "(error) key doesn't contain a graph object", singular rather than plural.

**Comment by kdaham** [comment]
Mainly because of existing code(using geo, hset, json), overall jedis and lettuce seems quite similar, easy to extend which I have done using lettuce with a simple builder for creating graph queries. But yeah already had used lettuce for other parts.

**Comment by itamarhaber** [comment]
@swilley22 going back to the original issue - we know that weird things happen when a simple string Redis reply (afair errors are such) contain newlines.

P.s. weird as in breaks everything, not just lettuce.

**Comment by jeffreylovitz** [comment]
Oh, really? I wasn't aware of that. Is `ReplyWithStringBuffer` just a better choice whenever we might be returning user input?

**Comment by itamarhaber** [comment]
That, or perhaps sanitizing the input before you output it.

**Comment by swilly22** [comment]
Fix #150
